### ISSUE TITLE
Epic: August Roadmap

### ISSUE THREAD

**Issue by wesfloyd** [Layr-Labs/hello-world-avs#43]
Theme: get the local developer builds working correctly to simplify end user support.

Tasks:

- [x] Update this README.md immediately to communicate that Holesky support is "coming soon" and reduce inbound tickets.
- [x] https://github.com/Layr-Labs/hello-world-avs/issues/35
- [x] https://github.com/Layr-Labs/hello-world-avs/issues/36
  - [x] Related: https://github.com/Layr-Labs/hello-world-avs/issues/39
- [x] https://github.com/Layr-Labs/hello-world-avs/issues/41
